spring.application.name=bookstore

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.key=${API_KEY}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Enable debug logging for security to troubleshoot 403 issues
logging.level.com.example.bookstore.security=DEBUG
logging.level.org.springframework.security=DEBUG

# Bakong Individual Account Configuration
bakong.account.id=soeun_sovannarith@aclb
bakong.account.phone=85516992144
bakong.acquiring.bank=ACLEDA
bakong.merchant.name=BookHaven
bakong.merchant.city=Phnom Penh
bakong.store.label=BookHaven Online Store
bakong.terminal.label=Web Terminal 01
bakong.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMzEzZGE0ZDYyNDFhNGI4MyJ9LCJpYXQiOjE3NjQzMTgzMTYsImV4cCI6MTc3MjA5NDMxNn0.3f_u7vjtRNtTy4u-PrHbMnvnxxtOfnpk91pVcFor8QY

# Stripe Payment Configuration
stripe.api.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
